### ISSUE TITLE
Would you address IK?

### ISSUE THREAD

**Issue by GeorgeS2019** [ywmaa/Advanced-Movement-System-Godot#11]
As suggested here: [IK and Physical Bone Improvements](https://github.com/godotengine/godot-proposals/issues/750)

**Comment by ywmaa** [comment]
I already issued about constraints in godot proposal, I don't think I will work on it by myself , because I am trying to work on motion matching and distance matching 

but I am trying to help in testing 


for IK blending I will try and find a solution when I get some animations working on the character, if I do it I may be able to help integrating it directly in godot

**Comment by ywmaa** [comment]
@GeorgeS2019 

I commented in the issue with the code that I can help with .

so closing this as this feature should be done in Godot directly, if someone wants to suggest stuff about IK maybe they can suggest in the issue above
