### ISSUE TITLE
issue with "fire" event and errors in "LookAtObject"

### ISSUE THREAD

**Issue by metanoder** [ywmaa/Advanced-Movement-System-Godot#26]
Hi ywmaa,

Just started trying out your plug in for AMSG in the latest beta11.  Pretty amazing movement system plugin. 

Had a little problem getting it to work when I tried moving it to my project.  So instead, I tried just making a new project to see it would play  

I got it to play, but there's a bit of a problem with the "fire" event and errors piling up in the debugger for "LookAtObject".  
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/117393840/212246808-1fd8138a-fe3d-4b04-b7ee-8b8eea65b0ca.png">

When I hit fire, it flags an error.  
<img width="949" alt="image" src="https://user-images.githubusercontent.com/117393840/212246887-3afe8e16-dea3-4624-b07e-0a2cea34e43b.png">

Running doesn't seem to work either. 

I know beta11 just released, but just wanted to flag it as I was testing it for my project.  
Again, it's a phenomenal plug in for godot 4, thank you for offering it to the community 🍻🙏🏼.

**Comment by ywmaa** [comment]
I will look into the LookAtObject error and try to fix it.

**Comment by metanoder** [comment]
Thank you for the guidance!  🍻

**Comment by ywmaa** [comment]
@metanoder 
it should be fixed(the error won't show) in the last commit(which I did update in it the project to Godot 4 Beta 12 too).

also if you want to try IK System I disabled it, because currently ModificationStack for the skeleton is messy, and It had bugs as I remember in Beta 1, so no IK system in this project until I figure it out properly.

**Comment by ywmaa** [comment]
also I found that Modification Stack is currently removed from Godot 4 until they reimplement it in Godot 4.x
https://github.com/godotengine/godot/pull/71137

I agree on this because Modification Stack 3D was really unstable at all.
currently I will try SkeletonIK3D node, until Godot gets ModificationStack3D Node.

**Comment by metanoder** [comment]
ywmaa, you're amazing!  Can't thank you enough for making such a awesome 3rd person movement system!

> @metanoder it should be fixed(the error won't show) in the last commit(which I did update in it the project to Godot 4 Beta 12 too).
> 
> also if you want to try IK System I disabled it, because currently ModificationStack for the skeleton is messy, and It had bugs as I remember in Beta 1, so no IK system in this project until I figure it out properly.
